ci: check for english spelling errors
Run codespell against all source code in the lint target. Also check
that commit titles and bodies are free of spelling errors.

Signed-off-by: Robin Jarry <robin@jarry.cc>

diff --git a/devtools/check-patches b/devtools/check-patches
--- a/devtools/check-patches
+++ b/devtools/check-patches
@@ -117,6 +117,11 @@ for rev in $revisions; do
 	if [ "$(echo "$body" | wc -w)" -lt 3 ]; then
 		err "body has less than three words, please describe your changes"
 	fi
+
+	if ! git log --format='%s%n%b' -1 "$rev" | codespell -; then
+		err "spelling errors in title and/or body"
+	fi
+
 	if ! [ "$(git log --format='%P' -1 "$rev" | wc -w)" = 1 ]; then
 		err "merge commit found, please rebase your code"
 	fi
